wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.9
    start_time: 1657603253
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 19
      4: 3.6.9
      5: 0.12.21
      8:
      - 3
      - 5
batch_size:
  desc: null
  value: 32
embedding_length:
  desc: null
  value: 300
epochs:
  desc: null
  value: 10
hidden_size:
  desc: null
  value: 256
input_size:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 2.0e-05
output_size:
  desc: null
  value: 2
